### ISSUE TITLE
update conda-forge package to v2.0.0

### ISSUE THREAD

**Issue by mapo9** [conda-forge/backports-datetime-fromisoformat-feedstock#7]
### Comment:

Hi,
I was wondering why the v2.0.0 is not available on conda-forge, even though the recipe was updated here. 
A package I am currently creating on bioconda requires backports-datetime-fromisoformat but is not compatible to version 1.
Could you update the package retrievable via conda-forge to version 2?

Greetings,
Mark

**Comment by mapo9** [comment]
Hi @ocefpaf, 

could you please check out the problem and maybe add the new version? I really need it for another tool.

**Comment by ocefpaf** [comment]
The PR was issued, see #6, but looks like the CIs did not run on `main`. Let's try to re-render and see how it goes. See #8

**Comment by ocefpaf** [comment]
Look like we already dropped py 3.7. So we cannot build this at this time.

**Comment by xylar** [comment]
It looks like this got successfully built in the end.  Can this be closed?

**Comment by xylar** [comment]
I'm closing this because I think it's taken care of.  Please reopen if I'm mistaken about that.
